export default {
  Departure: 'departure',
  Department: 'department',
  Courier: 'courier',
  Fio: 'fio',
  Doc: 'doc',
  DocNumber: 'doc-number',
  Tel: 'tel',
  Street: 'street',
  Building: 'building',
  Apartment: 'apartment',
  CourierTime: 'courier-time',
  Author: 'author',
  FirstName: 'first-name',
  MiddleName: 'middle-name',
  LastName: 'last-name',
  Email: 'email',
  Role: 'role',
  CompanyName: 'company-name',
  Address: 'address'
};
